// Designed by TEAM 4
/**
 * Standard offer structure — every agent (human or AI, in every scenario)
 * produces offers in exactly this shape. See types/negotiation.js for the
 * JSDoc typedef.
 *
 * Fields:
 *  - agent_id:   which agent made the offer
 *  - round:      which round it belongs to
 *  - value:      the numeric term being negotiated (price / salary / budget)
 *  - reason:     short natural-language justification generated by LLM reasoning layer
 *  - decision:   decision type ("accept" | "counteroffer" | "reject")
 *  - parameters: additional negotiation metrics/parameters
 *  - timestamp:  ISO 8601, set at creation time
 *
 * @param {{ agent_id: string, round: number, value: number, reason: string, decision?: string, parameters?: Object }} params
 * @returns {import('../types/negotiation').Offer}
 */
export function createOffer({ agent_id, round, value, reason, decision, parameters }) {
  return {
    agent_id,
    round,
    value: Math.round(value),
    reason,
    decision: decision || "counteroffer",
    parameters: parameters || {},
    timestamp: new Date().toISOString(),
  };
}
